services:
  smart-home-dashboard:
    container_name: smart-home-dashboard
    image: ghcr.io/daddelgreis74/smart-home-dashboard:${IMAGE_TAG}
    restart: ${RESTART_POLICY}
    network_mode: "host"
    ports:
      - "${PORT}:8443"
    volumes:
      - "${DATA_VOLUME}:/app/data"
    environment:
      - PORT=8443
      - HOST=0.0.0.0
