services:
  smart-home-dashboard:
    container_name: smart-home-dashboard
    build: .
    restart: unless-stopped
    # network_mode: "host"
    ports:
      - "8443:8443"
    volumes:
      # Mountet alle Konfigurationen, Kalender-Uploads (calendar.ics) und SSL-Zertifikate in einen lokalen Ordner
      - ./data:/app/data
    environment:
      - PORT=8443
      - HOST=0.0.0.0

